### ISSUE TITLE
Cant'use older SBETool versions with JDK 8 anymore

### ISSUE THREAD

**Issue by KowKiller** [real-logic/simple-binary-encoding#1013] opened 2024-08-26 13:41 UTC
Hi,

Today I had a problem in my Maven-based build pipeline due to this error:
`java.lang.UnsupportedClassVersionError: org/agrona/MutableDirectBuffer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

I am using SBE Tool 1.30.0 and I have not upgraded it.
After a bit of investigation, it seems that SBE Tool links a range of versions for Agrona, rather than a specific one, so now that version 1.23 has been released, Maven is picking that one as a dependency, breaking the build.

For now I found the following possible workarounds:
1. Changingthe  sbe-tool dependency to sbe-all, since the latter is an uber-jar with Agrona already included
2. Adding a fixed Agrona 1.22.0 dependency

Do you plan to release a fix for this?

Thanks

**Comment by vyazelenko** [comment] 2024-08-26 14:06
SBE defines a dependency on Agrona which imposes a minimum version requirement while allowing end users to upgrade their Agrona version independent of SBE releases.

As can be seen from the below in the Gradle build we clearly set an exact version (e.g. `1.20.0` for the SBE `1.30.0`):
```java
        api("org.agrona:agrona") {
            version {
                strictly(agronaVersionRange)
                prefer(agronaVersion)
            }
        }
```
However, looking at the [sbe-tool-1.30.0.pom](https://repo1.maven.org/maven2/uk/co/real-logic/sbe-tool/1.30.0/sbe-tool-1.30.0.pom) this then becomes:
```xml
<dependency>
  <groupId>org.agrona</groupId>
  <artifactId>agrona</artifactId>
  <version>[1.20.0,2.0)</version>
  <scope>compile</scope>
</dependency>
```
Which, I guess, is the reason why Maven is trying to pull the latest version of Agrona which is now requiring JDK 17 to compile and run.

The latest release of SBE that is based on JDK 8 is [1.32.2](https://github.com/real-logic/simple-binary-encoding/releases/tag/1.32.2) which uses [Agrona 1.22.0](https://github.com/real-logic/agrona/releases/tag/1.22.0). Whereas [1.33.0](https://github.com/real-logic/simple-binary-encoding/releases/tag/1.33.0-v2) requires JDK 17 and uses [Agrona 1.23.0](https://github.com/real-logic/agrona/releases/tag/1.23.0-v2).

I do not think we can release a fix for this behavior given it is a build tool specific. Instead you would have apply one of the workarounds.

**Closed by vyazelenko** 2024-08-26 14:06 UTC

**Comment by vyazelenko** [comment] 2024-08-26 14:35
@KowKiller The problem is actually a lack of explicit dependency on Agrona, i.e. SBE is a compile-only dependency but the code it generates depends on Agrona API. Therefore, an explicit Agrona dependency is required which also fixes the underlying issue.

**Comment by KowKiller** [comment] 2024-08-26 17:08
Thanks, I updated my pom to use an explicit Agrona dependency.
