### ISSUE TITLE
[C++] Use strongly typed enums in generated code

### ISSUE THREAD

**Issue by rigtorp** [real-logic/simple-binary-encoding#710] opened 2019-08-26 21:08 UTC
Using enum class could improve type safety in the C++ API. It would also be a API breakage.Something to consider for the future.

**Comment by mjpt777** [comment] 2020-09-07 18:46
Duplicate of https://github.com/real-logic/simple-binary-encoding/issues/690

**Closed by mjpt777** 2020-09-07 18:46 UTC
