### ISSUE TITLE
Generated C++ code for variable length data may not compile 

### ISSUE THREAD

**Issue by rogerorr** [real-logic/simple-binary-encoding#796] opened 2020-06-23 11:56 UTC
There seems to be a potential case mismatch when using a schema file with a variable length field.

There is inconsistent handling of the case of the first letter of the field name.

The C++ generated code creates an accessor method such as:
  `static SBE_CONSTEXPR std::uint64_t exampleHeaderLength() SBE_NOEXCEPT`
but then attempts to call it inside:
  `SBE_NODISCARD static size_t computeLength(std::size_t ExampleLength = 0)`
by invoking it as:
  `length += ExampleHeaderLength();`

I encountered the issue updating from 1.12.2 to 1.82.2 and have reproduced it with the current code by changing the case of the last field in `sbe-tool/src/test/resources/code-generation-schema.xml` from "color" to "Color":

`java -Dsbe.target.language=CPP -Dsbe.target.namespace=test -jar sbe-all/build/libs/sbe-all-1.19.0-SNAPSHOT.jar sbe-tool/src/test/resources/code-generation-schema.xml` 

Testing the output:

```
g++ -c test/Car.h
test/car.h: In static member function 'static size_t test::Car::computeLength(const std::vector<std::tuple<long unsigned int> >&, const std::vector<std::tuple<long unsigned int> >&, std::size_t, std::size_t, std::size_t, std::size_t)':
test/car.h:3202:15: error: 'ColorHeaderLength' was not declared in this scope; did you mean 'colorHeaderLength'?
 3202 |     length += ColorHeaderLength();
      |               ^~~~~~~~~~~~~~~~~
      |               colorHeaderLength
```

**Comment by mjpt777** [comment] 2020-06-23 12:15
This is a duplicate of https://github.com/real-logic/simple-binary-encoding/issues/795 which has been fixed and will make the next release.

**Comment by rogerorr** [comment] 2020-06-23 13:33
This problem does not appear to be fixed by the resolution of #795.

(1) The example change of "color" -> "Color" in the test schema still generates bad code with the current master (3b0d3f6).

(2) #795 _is_ referring to the same method but it is describing a _different_ problem -- an interaction with `constexpr`.

**Comment by mjpt777** [comment] 2020-06-23 15:03
@rogerorr Try building with head now.

**Comment by rogerorr** [comment] 2020-06-23 17:02
Thanks, the codegen looks good now.

**Closed** 2020-06-23 17:03 UTC
